dev-casbin-mysql:
  image: mysql:5.7
  container_name: dev-casbin-mysql
  command: mysqld --character-set-server=utf8mb4
  environment:
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_PORT: 3306
    MYSQL_DATABASE: development
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    TZ: "Asia/Tokyo"
  ports:
    - 3306:3306
